apiVersion: apps/v1
kind: Deployment
metadata:
  name: puzzle-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzle-game
  template:
    metadata:
      labels:
        app: puzzle-game
    spec:
      containers:
      - name: puzzle-game
        image: puzzle-game:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: puzzle-game
spec:
  type: NodePort
  selector:
    app: puzzle-game
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32001
